### PR TITLE
Adding more translations for Japanese.

### PR DESCRIPTION
**Pull request by wico-**
More translations for JP. Should be just one or two more batches.

### CODE REVIEW

**Comment by marquesinijatinha** [comment]
hey @wico- seems like this conflicts with master
can you pull the latest version and send a new PR ?

**Comment by wico-** [comment]
For sure! I'll do it tonight.

2019年8月12日(月) 12:06 João Paulo <notifications@github.com>:

**Comment by marquesinijatinha** [comment]
oh btw, @RaSSieL86 just told me he integrated your translations in the new platform thing
no need to send another PR then, translations will probably be moved away from github if we suceed on the new tool

**Comment by wico-** [comment]
Awesome! :D

Thanks much! Sorry for the trouble.

2019年8月12日(月) 13:33 João Paulo <notifications@github.com>:

**Pull request closed without merging**
